###服务端口号
server:
    port: 8000
##定义服务名称
spring:
    application:
        name: tamalecloud-eureka-server
eureka:
    instance:
        ###注册中心ip地址
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        ###是否需要将自己注册给自己的注册中心,因为自己是注册中心所以设置false（集群的时候是需要是为true）
        register-with-eureka: false
        ###是否需要去检索服务信息，因为自己是注册中心所以设置false（集群的时候是需要是为true）
        fetch-registry: false
    server:
        ###自我保护模式（缺省为打开）开发时候时候关闭自我保护机制，方便测试。让Eureka及时清理掉已经关闭的服务。生产环境打开。
        enable-self-preservation: false
        ###主动清理无效节点的时间间隔，默认60000毫秒，即60秒
        eviction-interval-timer-in-ms: 2000
        ###server端更新緩存的间隔默认30秒
        responseCacheUpdateIntervalMs: 1000