###服务启动端口号
server:
  port: 8911
###服务名称(服务注册到eureka名称) 
spring:
    application:
        name: tamalecloud-config-server
    profiles:
        active: native
---
###从本地读取配置信息
spring:
    profiles: native
    cloud:
       config:
          server:
             native:
                search-locations: classpath:/config #配置文件存放的目录
                 ### 有目录的时候需要加这个 label: main
---
###从git检索信息
spring:
    profiles: git
    cloud:
       config:
          server:
             git:
                uri: https://github.com/howard-com/tamalecloud_config.git
                default-label: main
                #searchpath: -tamalecloud_config_cen
---
eureka:
   instance:
      ###心跳（续约）间隔时间，默认90s, 可不配置
      lease-renewal-interval-in-seconds: 1
      ###发呆（过期）时间，心跳停止超过此时间后服务会被Eureka server剔除，默认30s，可不配置
      lease-expiration-duration-in-seconds: 2
   client:
      service-url:
         defaultZone: http://localhost:8000/eureka
      ###是否需要从eureka上获取注册信息
      fetch-registry: false
      ###注册到注册中心
      register-with-eureka: true
      ###Enreka客户端多久去server上拉去一次列表（定时刷新本地缓存时间），默认为90秒
      registry-fetch-interval-seconds: 10
      ###最初复制实例信息到eureka服务器所需的时间（s），默认为40秒
      initial-instance-info-replication-interval-seconds: 1