server:
  port: 9000

## hystrix 信号量隔离，3秒后自动超时
#hystrix:
#   command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 1000
#   shareSecurityContext: true

#test:
  #  hostport: httpbin.org:80
  #  hostport: localhost:5000
  #  uri: http://${test.hostport}
#  uri: lb://httpbin

spring:
  application:
    name: tamalecloud-gateway
#  jmx:
#    enabled: false
  cloud:
    circuitBreaker:
        resilience4j:
            enabled: true
    gateway:
      default-filters:
       - AuthCheck
       - TamaleBase
       # 熔断降级配置
       - name: CircuitBreaker
         args:
           name: fallbackcmd
           fallbackUri: forward:/error/fallback
#      - PrefixPath=/httpbin
#      - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
      # =====================================
      # to run server
      # $ wscat --listen 9000
      # to run client
      # $ wscat --connect ws://localhost:8080/echo
      - id: entity-service
        uri: lb://${entity_service_name}
        order: 1000
        predicates:
        - Path=/Entity/**
        filters:
        #去掉路径的前缀再转发给Entity service
        - StripPrefix=1
      # =====================================
      - id: entry-service
        uri: lb://${entry_service_name}
        order: 1000
        predicates:
        - Path=/Entry/**
        filters:
        #去掉路径的前缀再转发给Entry service
        - StripPrefix=1
      - id: cache-service
        uri: lb://${cache_service_name}
        order: 1000
        predicates:
        #去掉路径的前缀再转发给Cache service
        - Path=/Cache/**
        filters:
        - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
